name: build and deploy product-catalog microservice

on:
  push:
    branches:
      - main

jobs:
  build-product-catalog:
    runs-on: ubuntu-latest

    steps:
      - name: checkout product-catalog only
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src/product-catalog
          sparse-checkout-cone-mode: false

      - name: Setup Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: build
        run: |
          cd src/product-catalog
          go mod download
          go build -o product-catalog-service main.go

      - name: unit tests
        run: |
          cd src/product-catalog
          go test ./...

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: checkout product-catalog only
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src/product-catalog
          sparse-checkout-cone-mode: false

      - name: setup Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.55.2
          run: golangci-lint run
          working-directory: src/product-catalog

  build-docker-image:
    runs-on: ubuntu-latest

    needs: build-product-catalog

    steps:
      - name: checkout product-catalog only
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src/product-catalog
          sparse-checkout-cone-mode: false

      - name: install Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          logout: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: src/product-catalog
          push: true
          file: src/product-catalog/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{github.run_id}}
